automation:
  #binary_sensor.rorelsesensor_uppe_2
  - alias: Turn on light when there is movement in the hall
    trigger:
      platform: state
      entity_id: binary_sensor.rorelsesensor_uppe_2
      to: 'on'
    condition: 
      - condition: state
        entity_id: 'sensor.house_mode'
        state: 'Natt'
    action:
        service: light.turn_on
        entity_id: light.hallenuppe

  - alias: Turn off light when there is no movement in the hall
    trigger:
      platform: state
      entity_id: binary_sensor.rorelsesensor_uppe_2
      to: 'off'
      for:
        minutes: 20
    condition: 
      - condition: state
        entity_id: 'sensor.house_mode'
        state: 'Natt'
    action:
      service: light.turn_off
      entity_id: light.hallenuppe


  - alias: Turn on light when there is movement in TV-rummet nere
    trigger:
      platform: state
      entity_id: binary_sensor.rorelsesensor_nere_2
      to: 'on'
    condition: 
      - condition: state
        entity_id: 'sensor.house_mode'
        state: 'Natt'
    action:
        service: light.turn_on
        entity_id: light.tvnere_fonster

  - alias: Turn off light when there is no movement in TV-rummet nere
    trigger:
      platform: state
      entity_id: binary_sensor.rorelsesensor_nere_2
      to: 'off'
      for:
        minutes: 20
    condition: 
      - condition: state
        entity_id: 'sensor.house_mode'
        state: 'Natt'
    action:
      service: light.turn_off
      entity_id: light.tvnere_fonster