homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 49
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_named themes
# Enables configuration UI
config:


http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 3
  use_x_forwarded_for: True
  trusted_proxies: 192.168.1.5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery: # Set this on to discover new devices. I have it off to make system more responsive

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret maria_db_url
  include:
    domains:
      - climate
    entities:
      - input_select.house_mode_select
      - media_player.melkers_tv
      # tracking
      - sensor.presence_elin
      - sensor.presence_tomas
      - sensor.presence_sally
      - sensor.presence_melker
      - sensor.sally_phone_mqtt_bt
      - sensor.melker_phone_mqtt_bt
      - sensor.tomas_phone_mqtt_bt
      - sensor.elin_phone_mqtt_bt
      - proximity.prox_home_tomas
      - proximity.prox_home_elin

      # sensors of interest
      - sensor.utetemp_temperature
      - sensor.utetemp_humidity
      - sensor.temp_outside
      - sensor.hum_outside
      - sensor.frysnere_temperature  #Frys nere
      - sensor.frysuppe_temperature  #Frys uppe
      - sensor.temp_sovrum_nere
      - sensor.temp_vardagsrum_uppe
      - sensor.temp_sallysrum
      - sensor.temp_elins_rum
      - sensor.temp_frys_uppe
      - binary_sensor.ytterdorr_uppe
      - sensor.occupancy

#logger:
#  default: debug
#  default: info
# Enables support for tracking state changes over time
history:
  
# View all events in a logbook
logbook:

influxdb:
  
  username: !secret influx_username
  password: !secret influx_password
  include:
#    domains:
#      - climate
#      - device_tracker
#      - sensor
#      - remote 
#      - media_player
#      - input_select  
#      - binary_sensor
    entities:
      - input_select.house_mode_select
      - media_player.melkers_tv
      - media_player.tv_nere
      # tracking
      - sensor.presence_elin
      - sensor.presence_tomas
      - sensor.presence_melker
      - sensor.presence_sally
      - sensor.tomas_phone_mqtt_bt # just for reference remove later
      - device_tracker.tomass8  # just for reference remove later
      - device_tracker.tomasgps # just for reference remove later
      - sensor.occupancy
      
      # sensors of interest
      - sensor.utetemp_temperature
      - sensor.utetemp_humidity
      - sensor.frysnere_temperature  #Frys nere
      - sensor.frysuppe_temperature  #Frys uppe
      - sensor.temp_sovrum_nere
      - sensor.temp_vardagsrum_uppe
      - sensor.temp_sallysrum
      - sensor.temp_elins_rum
      - sensor.temp_frys_uppe
      - binary_sensor.ytterdorr_uppe
      - sensor.kamera_uppe_light_sensor
      - switch.computer_tomas
      - remote.tvroom 
      - binary_sensor.rorelsesensor_uppe
      # nuc stats
      - sensor.memory_use_percent
      - sensor.processor_use
      

# Enables a map showing the location of tracked devices
map:

sensor:
  - platform: time_date

# Text to speech
tts:
  - platform: google
    language: 'sv'
    cache: false
    time_memory: 600

hassio:    

mqtt:
  broker: !secret mqqtt_broker
  discovery: true
  discovery_prefix: homeassistant
  username: !secret mqtt_user
  password: !secret mqtt_password

#tuya:
#  username: 54321
#  password: 12345
#  country_code: 46
#cloud:

zone: !include zones.yaml
group: !include groups.yaml
