resources:
  - url: /local/picture-entity-status.js?v=1.27
    type: module

title: Hellströms home


views:
    # View tab title.
  - title: Information
    # Optional unique id for direct access /lovelace/${id}
    id: info
    icon: mdi:information-outline
    cards:
      - type: vertical-stack
        cards:
        #
        # PRESENCE INFORMATION
        #
        - type: horizontal-stack
          cards:
            - type: custom:picture-entity-status
              entity: sensor.presence_tomas
              image: /local/tomas_presence_away.jpg
              state_image:
                Home: /local/tomas_presence.jpg
                Just arrived: /local/tomas_presence.jpg
              name: ' '
              style: '#name { display: none;}'
            - type: custom:picture-entity-status
              entity: sensor.presence_elin
              image: /local/elin_presence_away.jpg
              state_image:
                Home: /local/elin_presence.jpg
                Just arrived: /local/elin_presence.jpg
              name: ' '
            - type: custom:picture-entity-status
              entity: sensor.presence_sally
              image: /local/sally_presence_away.jpg
              state_image:
                Home: /local/sally_presence.jpg
                Just arrived: /local/tomas_presence.jpg
              name: ' '
            - type: custom:picture-entity-status
              entity: sensor.presence_melker
              image: /local/melker_presence_away.jpg
              state_image:
                Home: /local/melker_presence.jpg
                Just arrived: /local/melker_presence.jpg
              name: ' '
        #
        # Temperature and moisture plus current weather icons
        #
        - type: picture-elements
          image: /local/img/weather_bg.jpg
          elements:
            - type: state-label
              entity: sensor.temp_outside
              style:
                top: 47%
                left: 9.8%
                font-size: 150%
                font-weight: bold;
            - type: state-label
              entity: sensor.hum_outside
              style:
                top: 47%
                left: 24.8%
                font-size: 150%
                font-weight: bold;
            - type: state-icon
              entity: sensor.yr_symbol
              style:
                top: 52%
                left: 40%

        - type: picture-elements
          image: /local/img/first_floor.jpg
          elements:
          #
          # Living room 
          #
            - type: state-icon
              entity: binary_sensor.rorelsesensor_uppe
              style:
                top: 89.45%
                left: 8.42%
            - type: state-icon
              entity: binary_sensor.ytterdorr_uppe
              style:
                top: 10.5%
                left: 48.5%
            - type: state-icon
              entity: light.vardagsrummet_hoger
              style:
                top: 89.45%
                left: 17.9%
            - type: state-icon
              entity: light.vardagsrumet_mitten
              style:
                top: 89.45%
                left: 38.2%
            - type: state-icon
              entity: light.vardagsrummet_vanster
              style:
                top: 89.45%
                left: 60.5%   
            - type: state-icon
              entity: media_player.tv_uppe
              style:
                top: 54.45%
                left: 17.9%   
          #
          # Hallen uppe
          #
            - type: state-icon
              entity: light.hallenuppe_dorren
              style:
                top: 10.5%
                left: 55.5%             
            - type: state-icon
              entity: media_player.vardagsrum
              style:
                top: 19.5%
                left: 55.5%  
            - type: state-icon
              entity: light.hallenuppe
              style:
                top: 27.5%
                left: 55.5%             
          #
          # Tomas room
          #     
            - type: state-icon
              entity: binary_sensor.rorelsesensor_tomas_rum
              style:
                top: 44%
                left: 78.5%
            - type: state-icon
              entity: switch.switch1 #tomas room
              style:
                top: 10.5%
                left: 82.5%  
            - type: state-icon
              entity: switch.computer_tomas #tomas room
              style:
                top: 10.5%
                left: 92.2% 
            - type: state-icon
              entity: switch.switch4_tomas_fan #tomas room
              style:
                top: 20.5%
                left: 92.2% 
          #
          # Sallys room
          #
            - type: state-icon
              entity: binary_sensor.rorelsesensor_sallys_rum
              style:
                top: 44%
                left: 8.42%
            - type: state-icon
              entity: switch.switch2 #light sallys room window
              style:
                top: 10.5%
                left: 17.9%       
          #
          # kitchen
          #
            - type: state-icon
              entity: switch.switch6 #window
              style:
                top: 89.45%
                left: 78.2%  
            - type: state-icon
              entity: switch.switch7 #small windows
              style:
                top: 58.8%
                left: 92.4% 
            - type: state-icon
              entity: media_player.kitchen
              style:
                top: 89.45%
                left: 85.5%   
          #
          # Lower floor
          #
        - type: picture-elements
          image: /local/img/second_floor.jpg
          elements:
          #
          # Master bedroom 
          #
            - type: state-icon
              entity: switch.switch3 #bedroom light
              style:
                top: 90.2%
                left: 16.6%
            - type: state-icon
              entity: binary_sensor.rorelsesensor_sovrummet
              style:
                top: 90.2%
                left: 8.42%
            - type: state-icon
              entity: media_player.sovrum
              style:
                top: 90.2%
                left: 25.6%
          #
          # Tv room 
          #
            - type: state-icon
              entity: light.tvrummet_hoger
              style:
                top: 90.2%
                left: 47.2%
            - type: state-icon
              entity: light.tvrummet_vanster
              style:
                top: 90.2%
                left: 57.42%
            - type: state-icon
              entity: switch.switch10 # wall lights
              style:
                top: 50.8%
                left: 67%
            - type: state-icon
              entity: binary_sensor.rorelsesensor_nere
              style:
                top: 90.2%
                left: 33.42%
            - type: state-icon
              entity: media_player.tv_nere
              style:
                top: 50.8%
                left: 50%
            - type: state-icon
              entity: media_player.tv_rummet_gh
              style:
                top: 50.8%
                left: 59%
          #
          # Melkers room
          #
            - type: state-icon
              entity: binary_sensor.rorelsesensor_melkers_rum
              style:
                top: 90.2%
                left: 73.42%      
            - type: state-icon
              entity: media_player.melkers_tv
              style:
                top: 50.8%
                left: 92.4% 
            - type: state-icon
              entity: switch.switch8_melkers_tv # Melkers tv  
              style:
                top: 60.8%
                left: 92.4%
            - type: state-icon
              entity: switch.switch5_melkers_fan  
              style:
                top: 70.8%
                left: 92.4%   
    
  - icon: mdi:google-maps
    # Title of the view. Will be used as the tooltip for tab icon
    title: Karta
    cards:
        # Entities card will take a list of entities and show their state.
      - type: map
        # Title of the entities card
        title: My map
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - sensor.presence_sally
          - sensor.presence_tomas
          - sensor.presence_elin
          - sensor.presence_melker
            
