resources:
  - url: /local/picture-entity-status.js?v=1.27
    type: module

title: Hellströms home


views:
    # View tab title.
  - title: Information
    # Optional unique id for direct access /lovelace/${id}
    id: info
    icon: mdi:information-outline
    cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: custom:picture-entity-status
              entity: sensor.presence_tomas
              image: /local/tomas_presence_away.jpg
              state_image:
                Home: /local/tomas_presence.jpg
                Just arrived: /local/tomas_presence.jpg
              name: ' '
              style: '#name { display: none;}'
            - type: custom:picture-entity-status
              entity: sensor.presence_elin
              image: /local/elin_presence_away.jpg
              state_image:
                Home: /local/elin_presence.jpg
                Just arrived: /local/elin_presence.jpg
              name: ' '
            - type: custom:picture-entity-status
              entity: sensor.presence_sally
              image: /local/sally_presence_away.jpg
              state_image:
                Home: /local/sally_presence.jpg
                Just arrived: /local/tomas_presence.jpg
              name: ' '
            - type: custom:picture-entity-status
              entity: sensor.presence_melker
              image: /local/melker_presence_away.jpg
              state_image:
                Home: /local/melker_presence.jpg
                Just arrived: /local/melker_presence.jpg
              name: ' '
     
  - icon: mdi:google-maps
    # Title of the view. Will be used as the tooltip for tab icon
    title: Karta
    cards:
        # Entities card will take a list of entities and show their state.
      - type: map
        # Title of the entities card
        title: My map
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - sensor.presence_sally
          - sensor.presence_tomas
          - sensor.presence_elin
          - sensor.presence_melker
            
