#Determine the status of the house to control depending on day, night, evening and morgnin

input_select:
  house_mode_select:
    name: Husstatus
    options:
      - Dag
      - Natt
      - Kväll
      - Morgon


sensor:
  - platform: template
    sensors:
      house_mode:
        value_template: '{{ states.input_select.house_mode_select.state }}'
        friendly_name: 'Hus status'

automation:
# Set house modes depending on time and sun 
  - alias: "Set house mode to 'kväll'"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Kväll"
  
  - alias: "Set house mode to 'morgon'"
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:30:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Morgon"

  - alias: "Set house mode to 'Dag'"
    trigger:
      - platform: time
        at: '10:00:00'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Dag" 

  - alias: "Set house mode to 'Natt' weekdays"
    trigger:
      platform: time
      at: '23:30:00'
    condition:
      condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"

  - alias: "Set house mode to 'Natt' weekends"
    trigger:
      platform: time
      at: '00:15:00'
    condition:
      condition: time
      weekday:
        - fri
        - sat
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"

# Trigger different scenes depending on house mode
  - alias: "Trigger 'Natt'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Natt"
    action:
      - service: scene.turn_on
        entity_id: scene.Natt

  - alias: "Trigger 'Dag'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Dag"
    action:
      - service: scene.turn_on
        entity_id: scene.Dag

  - alias: "Trigger 'Kväll'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Kväll"
    action:
      - service: scene.turn_on
        entity_id: scene.Kvall

  - alias: "Trigger 'Morgon'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Morgon"
    action:
      - service: scene.turn_on
        entity_id: scene.Morgon
scene:
  # Daytime all switches / lights should be off
  - name: Dag
    entities:
      #övervåningen
      group.room_tomas: 
        state: off
      group.room_sally:
        state: off
      group.room_vardagsrum_uppe:
        state: off
      group.room_koket:
        state: off
      # Undervångingen
      group.room_tvnere:
        state: off

  # Night all switches / lights should be off
  - name: Natt
    entities:
      #övervåningen
      group.room_tomas: 
        state: off
      group.room_sally:
        state: off
      group.room_vardagsrum_uppe:
        state: off
      group.room_koket:
        state: off
      # Undervångingen
      group.room_tvnere:
        state: off

  # Morning all switches / lights should be off
  - name: Morgon
    entities:
      #övervåningen
      group.room_tomas: 
        state: off
      group.room_sally:
        state: off
      group.room_vardagsrum_uppe:
        state: off
      group.room_koket:
        state: off
      # Undervångingen
      group.room_tvnere:
        state: off

  # Evening all floors should be lit (based on sunset)
  - name: Kväll
    entities:
      #övervåningen
      group.room_tomas: 
        state: on
      group.room_sally:
        state: on
      group.room_vardagsrum_uppe:
        state: on
      group.room_koket:
        state: on
      # Undervångingen
      group.room_tvnere:
        state: on

script:
  setnightmode:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"