#Determine the status of the house to control depending on day, night, evening and morgnin

input_select:
  house_mode_select:
    name: Husstatus
    options:
      - Dag
      - Natt
      - Kväll
      - Morgon


sensor:
  - platform: template
    sensors:
      house_mode:
        value_template: '{{ states.input_select.house_mode_select.state }}'
        friendly_name: 'Hus status'

automation:
# Set house modes depending on time and sun 
  - alias: "Set house mode to 'kväll'"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Kväll"
  
  - alias: "Set house mode to 'morgon'"
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:30:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Morgon"

  - alias: "Set house mode to 'Dag'"
    trigger:
      - platform: time
        at: '10:00:00'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Dag" 

  - alias: "Set house mode to 'Natt' weekdays"
    trigger:
      platform: time
      at: '23:30:00'
    condition:
      condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"

  - alias: "Set house mode to 'Natt' weekends"
    trigger:
      platform: time
      at: '00:15:00'
    condition:
      condition: time
      weekday:
        - sat
        - sun
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"

# Trigger different scenes depending on house mode
  - alias: "Trigger 'Natt'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Natt"
    action:
      - service: script.set_house_mode_night

  - alias: "Trigger 'Dag'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Dag"
    action:
      - service: script.set_house_mode_day

  - alias: "Trigger 'Kväll'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Kväll"
    action:
      - service: script.set_house_mode_evening

  - alias: "Trigger 'Morgon'"
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: "Morgon"
    action:
      - service: script.set_house_mode_morning

script:
  set_house_mode_night:
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          # Övervåningen
          - group.room_tomas
          - group.room_sally
          - group.room_vardagsrum_uppe
          - group.room_koket
          # Undervångingen
          - group.room_tvnere

  set_house_mode_evening:
    sequence:
      - service: homeassistant.turn_on
        entity_id:
          # Övervåningen
          - group.room_tomas
          - group.room_sally
          - group.room_vardagsrum_uppe
          - group.room_koket
          # Undervångingen
          - group.room_tvnere  
  
  set_house_mode_day:
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          # Övervåningen
          - group.room_tomas
          - group.room_sally
          - group.room_vardagsrum_uppe
          - group.room_koket
          # Undervångingen
          - group.room_tvnere  

  set_house_mode_morning:
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          # Övervåningen
          - group.room_tomas
          - group.room_sally
          - group.room_vardagsrum_uppe
          - group.room_koket
          # Undervångingen
          - group.room_tvnere  
   
  setnightmode:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"          

