

group:

  people_status:
    name: Familjen hemmastatus
    entities:
      - sensor.presence_tomas
      - sensor.presence_elin
      - sensor.presence_test

  presence:
    name: Familjens devicestatus
    view: no
    icon: mdi:home-account
    entities:
      - group.tomas_devices
      - group.elins_devices
      - group.sallys_devices
      - group.melkers_devices

  # After this 
  test_devices:
    name: Test hemma
    view: no
    entities:
      - device_tracker.tomas_phone_bt
      - device_tracker.testgps

  tomas_devices:
    name: Tomas hemma
    view: no
    entities:
      - device_tracker.tomas_phone_bt
      - device_tracker.tomasgps
      - device_tracker.tomass8      


  elins_devices:
    name: Elin hemma
    view: no
    entities:
      - device_tracker.elins_phone_bt
      - device_tracker.elingps
      - device_tracker.elinss8  

  melkers_devices:
    name: Melker hemma
    view: no
    entities:
      - device_tracker.melkergps
      - device_tracker.samsunggalaxys7

  sallys_devices:
    name: Sally hemma
    view: no
    entities:
      - device_tracker.sallygps
      - device_tracker.huawei_p20_pro2d36a29977

automation:
  - alias: Send message on away-home notice Tomas
    trigger:
      - platform: state
        entity_id: sensor.presence_tomas 
    action:
      service: script.notify
      data_template:
        tell: th
        title: "{{trigger.to_state.attributes.friendly_name}} status"
        message: "{{trigger.to_state.attributes.friendly_name}} har status {{trigger.to_state.state}}"    

#- alias: Send message on away-home notice Elin
#  trigger:
#    - platform: state
#      entity_id: sensor.elin_status #, input_select.elin_status_dropdown
#  action:
#    service: script.notify
#    data_template:
#      tell: th
#      title: "{{trigger.to_state.attributes.friendly_name}} status"
#      message: "{{trigger.to_state.attributes.friendly_name}} har status {{trigger.to_state.state}}"    


# For tracking
device_tracker:
  - platform: nmap_tracker
    hosts:
      !secret devices_tracked
    track_new_devices: no
    interval_seconds: 15
    consider_home: 180
  - platform: mqtt
    devices:
      tomas_phone_bt: 'hassio/bt/device_tracker/tomas_s8'
      elins_phone_bt: 'hassio/bt/device_tracker/elins_s8'
  - platform: gpslogger
    password: !secret gpslogger_password      

