

group:

  people_status:
    name: Familjen hemmastatus
    entities:
      - sensor.presence_tomas
      - sensor.presence_elin
      - sensor.presence_sally
      - sensor.presence_melker

  presence:
    name: Familjens devicestatus
    view: no
    icon: mdi:home-account
    entities:
      - group.tomas_devices
      - group.elins_devices
      - group.sallys_devices
      - group.melkers_devices

  # # After this 
  # test_devices:
  #   name: Test hemma
  #   view: no
  #   entities:
  #     - sensor.tomas_phone_mqtt_bt
  #     - device_tracker.testgps

  tomas_devices:
    name: Tomas hemma
    view: no
    entities:
      - sensor.tomas_phone_mqtt_bt #Bluetooth
      - device_tracker.tomasgps
      - device_tracker.tomass8      


  elins_devices:
    name: Elin hemma
    view: no
    entities:
      - sensor.elin_phone_mqtt_bt
      - device_tracker.elingps
      - device_tracker.elinss8  

  melkers_devices:
    name: Melker hemma
    view: no
    entities:
      - device_tracker.melkergps
      - sensor.melker_phone_mqtt_bt
      - device_tracker.samsunggalaxys7

  sallys_devices:
    name: Sally hemma
    view: no
    entities:
      - device_tracker.huawei_p20_pro2d36a29977
      - sensor.sally_phone_mqtt_bt

automation:
  - alias: Send message on away-home notice Tomas
    trigger:
      - platform: state
        entity_id: sensor.presence_tomas 
    condition:
      - condition: template
        value_template: "{{ trigger.from_state != None and trigger.from_state.state != trigger.to_state.state }}"
    action:
      service: script.notify_greet
      data_template:
        person: Tomas
        title: "Tomas status {{trigger.to_state.state}}"
        message: "Tomas har ändrat tracking status från state {{trigger.from_state.state}} till state {{trigger.to_state.state}}!"    

# For aproximity
proximity:
  prox_home_elin: 
    ignored_zones:
      - sjukhuset
    devices:
      - sensor.presence_elin
    tolerance: 50
  prox_home_tomas: 
    ignored_zones:
      - spv
    devices:
      - sensor.presence_tomas
    tolerance: 50

    # For tracking
device_tracker:
  - platform: nmap_tracker
    hosts:
      !secret devices_tracked
    track_new_devices: no
    interval_seconds: 15
    consider_home: 180
  
    
#  - platform: mqtt
#    devices:
#      tomas_s8: 'hassio/bt/device_tracker/tomas_s8'
#      tomas_s8: 'hassio/bt/device_tracker/elins_s8'
  - platform: gpslogger
    password: !secret gpslogger_password      
 # - platform: bluetooth_tracker
  #- platform: google_maps
  #  username: !secret gu 
  #  password: !secret gp
sensor:
  - platform: mqtt
    name: tomas_phone_mqtt_bt
    state_topic: 'test/bluetooth/owner/house/A0:10:81:18:E9:AD'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes:
      - "confidence"

  - platform: mqtt
    name: elin_phone_mqtt_bt
    state_topic: 'test/bluetooth/owner/house/48:27:EA:3E:9F:8F'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes:
      - "confidence"

  - platform: mqtt
    name: melker_phone_mqtt_bt
    state_topic: 'test/bluetooth/owner/house/F8:E6:1A:9A:5C:86'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes:
      - "confidence"

  - platform: mqtt
    name: sally_phone_mqtt_bt
    state_topic: 'test/bluetooth/owner/house/A0:57:E3:15:DE:4E'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes:
      - "confidence"
  