sensor:
  - platform: template
    sensors:
      tomas_status:
        value_template: '{{ states.input_select.tomas_status_dropdown.state }}'
        friendly_name: 'Tomas presence sensor'
  - platform: template
    sensors:
      elin_status:
        value_template: '{{ states.input_select.elin_status_dropdown.state }}'
        friendly_name: 'Elin  presence sensor'
  - platform: template
    sensors:
      sally_status:
        value_template: '{{ states.input_select.sally_status_dropdown.state }}'
        friendly_name: 'Sally presence sensor'
  - platform: template
    sensors:
      melker_status:
        value_template: '{{ states.input_select.melker_status_dropdown.state }}'
        friendly_name: 'Melker presence sensor'
  - platform: template
    sensors:
      tomas_device_tracker:
        friendly_name: 'Tomas presence sensor 2'
        value_template: >-
          {% if is_state("device_tracker.tomas_phone_bt", "home") or is_state("device_tracker.tomasgps", "home") or is_state("device_tracker.tomass8", "home") %}
            Hemma
          {% else %}
          {% if is_state("device_tracker.tomasgps", "not_home") %}
            Borta
          {% else %} {{ states("device_tracker.tomasgps") }}
          {% endif %}
          {% endif %}
        icon_template: >-
          {% if is_state("device_tracker.tomas_phone_bt", "home") or is_state("device_tracker.tomasgps", "home") or is_state("device_tracker.tomass8", "home") %}
            mdi:home-circle
          {% else %}
          {% if is_state("device_tracker.tomasgps", "not_home") %}
            mdi:close-circle-outline
          {% else %}
            {% set zone = states.device_tracker.tomasgps.state %}
            {{ states.zone[zone].attributes.icon }}
          {% endif %}
          {% endif %}

input_select:
  tomas_status_dropdown:
    name: Tomas
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - SPV
      - Sjukhuset
      - Birsta
      - Matfors Skola
    initial: Home
  elin_status_dropdown:
    name: Elin
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - SPV
      - Sjukhuset
      - Birsta
      - Matfors Skola
    initial: Home
  sally_status_dropdown:
    name: Sally
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - SPV
      - Sjukhuset
      - Birsta
      - Matfors Skola
    initial: Home

  melker_status_dropdown:
    name: Melker
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - SPV
      - Sjukhuset
      - Birsta
      - Matfors Skola
    initial: Home
#zone_spv
#zone_sjukhuset
#zone_birsta

automation:
  - alias: "Enter Zone"
    trigger:
      - platform: state
        entity_id: device_tracker.tomasgps, device_tracker.elingps
    condition:
      condition: template
      value_template: "{{ trigger.to_state != 'home'}}"
    action:
    - service: input_select.select_option
      data_template:
          entity_id: >
            {% if trigger.entity_id == 'device_tracker.tomasgps' %}
              input_select.tomas_status_dropdown
            {% else %}
              input_select.elin_status_dropdown
            {% endif %}
          option: >
           {{ trigger.to_state.state | title }}


group:

  people_status:
    name: Familjen hemmastatus
    entities:
      - sensor.tomas_status
      - sensor.tomas_device_tracker
      - sensor.elin_status
      - sensor.sally_status
      - sensor.melker_status

  tomas_devices:
    name: Tomas hemma
    view: no
    entities:
      - device_tracker.tomas_phone_bt
      - device_tracker.tomasgps
      - device_tracker.tomass8      


  elins_devices:
    name: Elin hemma
    view: no
    entities:
      - device_tracker.elins_phone_bt
      - device_tracker.elingps
      - device_tracker.elinss8  

  melkers_devices:
    name: Melker hemma
    view: no
    entities:
      - device_tracker.melkergps
      - device_tracker.samsunggalaxys7

  sallys_devices:
    name: Sally hemma
    view: no
    entities:
      - device_tracker.sallygps
      - device_tracker.huawei_p20_pro2d36a29977

  presence:
    name: Familjens devicestatus
    view: no
    icon: mdi:home-account
    entities:
      - group.tomas_devices
      - group.elins_devices
      - group.sallys_devices
      - group.melkers_devices

# For tracking
device_tracker:
  - platform: nmap_tracker
    hosts:
      !secret devices_tracked
    track_new_devices: no
    interval_seconds: 15
    consider_home: 180
  - platform: mqtt
    devices:
      tomas_phone_bt: 'hassio/bt/device_tracker/tomas_s8'
      elins_phone_bt: 'hassio/bt/device_tracker/elins_s8'
  - platform: gpslogger
    password: !secret gpslogger_password      