

group:

  people_status:
    name: Familjen hemmastatus
    entities:
      - sensor.presence_tomas
      - sensor.presence_elin
      - sensor.presence_test

  presence:
    name: Familjens devicestatus
    view: no
    icon: mdi:home-account
    entities:
      - group.tomas_devices
      - group.elins_devices
      - group.sallys_devices
      - group.melkers_devices

  # After this 
  test_devices:
    name: Test hemma
    view: no
    entities:
      - device_tracker.tomas_s8
      - device_tracker.testgps

  tomas_devices:
    name: Tomas hemma
    view: no
    entities:
      - device_tracker.tomas_s8 #Bluetooth
      - device_tracker.tomasgps
      - device_tracker.tomass8      


  elins_devices:
    name: Elin hemma
    view: no
    entities:
      - device_tracker.elins_s8
      - device_tracker.elingps
      - device_tracker.elinss8  

  melkers_devices:
    name: Melker hemma
    view: no
    entities:
      - device_tracker.melkergps
      - device_tracker.samsunggalaxys7

  sallys_devices:
    name: Sally hemma
    view: no
    entities:
      - device_tracker.sallygps
      - device_tracker.huawei_p20_pro2d36a29977

automation:
  - alias: Send message on away-home notice Tomas
    trigger:
      - platform: state
        entity_id: sensor.presence_tomas 
    condition:
      - condition: template
        value_template: "{{ trigger.from_state != None and trigger.from_state.state != trigger.to_state.state }}"
    action:
      service: script.notify
      data_template:
        tell: th
        title: "Tomas status {{trigger.to_state.state}}"
        message: "Tomas har ändrat tracking status till {{trigger.to_state.state}} from state {{trigger.from_state.state}}"    

# For tracking
device_tracker:
  - platform: nmap_tracker
    hosts:
      !secret devices_tracked
    track_new_devices: no
    interval_seconds: 15
    consider_home: 180
#  - platform: mqtt
#    devices:
#      tomas_s8: 'hassio/bt/device_tracker/tomas_s8'
#      tomas_s8: 'hassio/bt/device_tracker/elins_s8'
  - platform: gpslogger
    password: !secret gpslogger_password      
  - platform: bluetooth_tracker
  - platform: google_maps
    username: !secret gu 
    password: !secret gp

  