
# Harmony multi
remote:
  - platform: harmony
    name: TVRoom
    host: !secret harmony
    activity: Plattan pa TV

group:
  # Remote controls
  remotes:
    name: Fjärrkontroller
    view: no
    entities:
      - remote.tvroom  

  # Media spelare
  googlehomes:
    name: Google homes
    view: no
    entities:
      - media_player.house
      - media_player.kitchen
      - media_player.sovrum
      - media_player.vardagsrum
      - media_player.tvroom

  chromecasts:
    name: Chrome casts
    view: no
    entities:
      - media_player.tv_nere
      - media_player.tv_uppe
      - media_player.melkers_tv

automation:
  - alias: "Chromcast TV Nere playing"
    trigger:
      - platform: state
        entity_id: media_player.tv_nere
        to: 'playing'
    action:
      - service_template: >
          {%- if is_state('remote.tvroom', 'off') -%}
            remote.turn_on
          {%- endif -%}
        entity_id: remote.tvroom
        data:
          activity: Plattan pa TV

  - alias: "Turn off TV-Nere if idle"
    trigger:
      - platform: state
        entity_id: media_player.tv_nere
        to: 'idle'
        for: '00:05:00'
    action:
      - service: homeassistant.off
        entity_id: remote.tvroom

  - alias: "Turn off TV-Nere if off"
    trigger:
      - platform: state
        entity_id: media_player.tv_nere
        to: 'off'
        for: '00:05:00'
    action:
      - service: homeassistant.off
        entity_id: remote.tvroom