rfxtrx:
  device: /dev/ttyUSB.RFX  #/dev/serial/by-id/usb-RFXCOM_RFXtrx433_A138UEXZ-if00-port0

sensor:
  - platform: rfxtrx
    automatic_add: True
    devices:
      08500703a70080fc59:
        name: frysnere
      08500702970080d669:
        name: frysuppe
      0a52099eb700005c490379:
        name: utetemp
        data_type:
          - Humidity
          - Temperature

switch:
  platform: rfxtrx
  automatic_add: False
  signal_repetitions: 4
  devices:
    0b11000402bc0cfe01010f70:
      name: testswitch
    0b11000451bc0cfe08010f70:
      name: switch1 #Julbelysning kök lilla fönster
    0b11000329bc0cfe06010f70:
      name: switch2
    0b11000115bc0cfe01010f70:
      name: switch3 # Julbelysning köket Rum           
    0b11000534bc0cfe06010f70:
      name: switch4_tomas_fan
    0b11000152bc0cfe01010f70:
      name: switch5_melkers_fan
    0b11000544bc0cfe01010f70:
      name: switch66 # Julbelysning kök
    0b11000693bc0cfe02010f70:
      name: switch7 # The switch for rpi with plex
    0b11000172bc0cfe02010f70:
      name: switch8_melkers_tv
    0b11000467bc0cfe04010f70:
      name: switch9outdoor
    0b11000555bc0cfe07010f70:
      name: switch10
    0b11000381bc0cfe01010f70:
      name: switch11 #Julbelysning vardagsrum vänster
    0b11000239bc0cfe07010f70:
      name: switch12 #Julbelysning vardagsrum mitten
    0b11000250bc0cfe08010f70:
      name: switch13 #Julbelysning vardagsrum höger
    0b11000163bc0cfe09010f70:
      name: switch14 #Julbelysning tvrum vänster
    0b11000136bc0cfe08010f70:
      name: switch15 #Julbelysning tvrum höger
    0b11000651bc0cfe04010f70:
      name: switch16 #Julbelysning sovrum fönster
    0b110000018ce3620b000060:
      name: switch_1_lb
    0b110010018ce3620c000070:
      name: switch_1_rb
    # Telldus small remote 1
    0b1100100294734610010f40:
      name: remote_1_b1
    0b11001c029473460f010f60:
      name: remote_1_b2
    0b110022029473460e010f60:
      name: remote_1_b3