
- alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: group.tomas_devices
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: group.elins_devices
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.tomas_devices' %}
            input_select.tomas_status_dropdown
          {% else %}
            input_select.elin_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'group.tomas_devices' %}
            {% if states.input_select.tomas_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.elin_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}

- alias: Mark Elin as home
  trigger:
    - platform: state
      entity_id: input_select.elin_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10 # change back to 10
    - platform: state
      entity_id: input_select.tomas_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10 # change back to 10        
    - platform: state
      entity_id: input_select.elin_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.tomas_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.elin_status_dropdown' %}
            input_select.elin_status_dropdown
          {% else %}
            input_select.tomas_status_dropdown
          {% endif %}
        option: Home

- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: group.tomas_devices
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: group.elins_devices
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.tomas_devices' %}
            input_select.tomas_status_dropdown
          {% else %}
            input_select.elin_status_dropdown
          {% endif %}
        option: Just Left

- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.tomas_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10 # change back to 10 minutes
    - platform: state
      entity_id: input_select.elin_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10 # change back to 10 minutes
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.tomas_status_dropdown' %}
            input_select.tomas_status_dropdown
          {% else %}
            input_select.elin_status_dropdown
          {% endif %}
        option: Away

- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.tomas_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.elin_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.tomas_status_dropdown' %}
            input_select.tomas_status_dropdown
          {% else %}
            input_select.elin_status_dropdown
          {% endif %}
        option: Extended Away

- alias: Send message on away-home notice Tomas
  trigger:
    - platform: state
      entity_id: sensor.tomas_status #, input_select.elin_status_dropdown
  action:
    service: script.notify
    data_template:
      tell: th
      title: "{{trigger.to_state.attributes.friendly_name}} status"
      message: "{{trigger.to_state.attributes.friendly_name}} har status {{trigger.to_state.state}}"    

- alias: Send message on away-home notice Elin
  trigger:
    - platform: state
      entity_id: sensor.elin_status #, input_select.elin_status_dropdown
  action:
    service: script.notify
    data_template:
      tell: th
      title: "{{trigger.to_state.attributes.friendly_name}} status"
      message: "{{trigger.to_state.attributes.friendly_name}} har status {{trigger.to_state.state}}"    

#binary_sensor.rorelsesensor_uppe
- alias: Turn on light when there is movement in the hall
  trigger:
    platform: state
    entity_id: binary_sensor.rorelsesensor_uppe
    to: 'on'
  condition: 
    - condition: state
      entity_id: 'sensor.house_mode'
      state: 'Natt'
  action:
      service: light.turn_on
      entity_id: light.hallenuppe

- alias: Turn off light when there is no movement in the hall
  trigger:
    platform: state
    entity_id: binary_sensor.rorelsesensor_uppe
    to: 'off'
    for:
      minutes: 20
  condition: 
    - condition: state
      entity_id: 'sensor.house_mode'
      state: 'Natt'
  action:
    service: light.turn_off
    entity_id: light.hallenuppe


- alias: Turn on light when there is movement in TV-rummet nere
  trigger:
    platform: state
    entity_id: binary_sensor.rorelsesensor_nere
    to: 'on'
  condition: 
    - condition: state
      entity_id: 'sensor.house_mode'
      state: 'Natt'
  action:
      service: light.turn_on
      entity_id: light.tvrummet_nere

- alias: Turn off light when there is no movement in TV-rummet nere
  trigger:
    platform: state
    entity_id: binary_sensor.rorelsesensor_nere
    to: 'off'
    for:
      minutes: 20
  condition: 
    - condition: state
      entity_id: 'sensor.house_mode'
      state: 'Natt'
  action:
    service: light.turn_off
    entity_id: light.tvrummet_nere