

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr # Wheather
    monitored_conditions:
      - temperature
      - symbol

group:
  # För givare och väder    
  climate:
    name: Klimat
    view: no
    entities:
      - sensor.ute_temperature
      - sensor.ute_humidity
      - sun.sun
      - sensor.yr_symbol
