automation:
  #Switch tv-room downstairs
  - alias: "Switch Sätt på lampor nere i fönstret"
    trigger:
      - platform: state
        entity_id: switch.switch_1_lb
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        entity_id:  light.tvnere_fonster

  - alias: "Switch Släck lampor nere i fönstret"
    trigger:
      - platform: state
        entity_id: switch.switch_1_lb
        from: "on"
        to: "off"
    action:
      - service: light.turn_off
        entity_id: light.tvnere_fonster

  - alias: "Switch Turn on TV"
    trigger:
      - platform: state
        entity_id: switch.switch_1_rb
        from: "off"
        to: "on"
    action:
      - service: homeassistant.turn_on
        entity_id: remote.tvroom

  - alias: "Switch Turn off TV"
    trigger:
      - platform: state
        entity_id: switch.switch_1_rb
        from: "on"
        to: "off"
    action:
      - service: homeassistant.turn_off
        entity_id: remote.tvroom