sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: since_last_boot


group:
  system_metrix:
    name: Systemparametrar
    icon: mdi:pi-box
    entities:
      - sensor.processor_use
      - sensor.disk_use_percent_home
      - sensor.memory_use_percent
      - sensor.since_last_boot
      - sensor.ha_uptime
      - sensor.cpu