#Duck dns
#duckdns:
#  domain: ha-hellstrom
#  access_token: 84f27be9-d7b7-4a29-814e-78349bbd3d6c


sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: since_last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0

group:
  system_metrix:
    name: Systemparametrar
    icon: mdi:pi-box
    entities:
      - sensor.processor_use
      - sensor.disk_use_percent_home
      - sensor.memory_use_percent
      - sensor.since_last_boot
      - sensor.ha_uptime
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.cpu